apiVersion: v1
kind: Service
metadata:
  name: kibana2
  namespace: kube-logging
  labels:
    app: kibana2
spec:
  ports:
  - port: 5601
  selector:
    app: kibana2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana2
  namespace: kube-logging
  labels:
    app: kibana2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana2
  template:
    metadata:
      labels:
        app: kibana2
    spec:
      containers:
      - name: kibana2
        image: docker.elastic.co/kibana/kibana:7.8.1
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://35.224.78.55:9200
        ports:
        - containerPort: 5601
